import "./globals.css";
import Navbar from "@/components/Navbar";
import SessionProvid from "@/components/SessionProvid";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SessionProvid>
        <Navbar></Navbar>
        {children}
        </SessionProvid>
      </body>
    </html>
  );
}
